### ISSUE TITLE
Comparing multiple functions over inputs

### ISSUE THREAD

**Issue by torkleyy** [japaric/criterion.rs#101]
Hey, this is a really great library! It's sad that it doesn't receive more attention in the Rust community.

Is there a way to compare how multiple functions behave over different input values? So basically I want `Criterion::bench_functions` and `Criterion::bench_function_over_input` combined.

**Comment by bheisler** [comment]
Thanks! Hopefully it attracts more attention once it's compatible with stable builds of Rust.

At some point I'll probably rework the interface to enable better support of more complex use cases like this, but until then I think this is a reasonable thing to add. In the meantime, you could maybe get away with calling `bench_function_over_inputs` multiple times, like so:

```rust
let params = ...
criterion.bench_function_over_inputs("MyFunc1", |b| b.iter(myfunc1), &params)
         .bench_function_over_inputs("MyFunc2", |b| b.iter(myfunc2), &params)
```

It wouldn't generate the same plots, but it would at least give roughly the same command-line output.

**Comment by bheisler** [comment]
I've reworked Criterion.rs' API to enable this use case better. An example is below:

    let parameters = vec![5, 10];
    let mut benchmark = ParameterizedBenchmark::new("print", |b, i| b.iter(|| print!("{}", i) ), parameters)
        .with_function("format", |b, i| b.iter(|| format!("{}", i));

    short_benchmark()
        .bench("test_bench_param", benchmark);
