### ISSUE TITLE
benchmarking within src

### ISSUE THREAD

**Issue by Eh2406** [japaric/criterion.rs#103]
Hi,

I have a project that has benchmark test in `src/fow/bar/bench.rs` so that it can test private items in `src/fow/bar/mod.rs` I try to convert to criterion, but did not find documentation on how to set up this use case. I am ok weather this is easy, hard, or not doable, but whichever it is it should be documented.

**Comment by bheisler** [comment]
Hmm, that's a fair point. I don't think that's currently supported. I'm not sure if it's possible to remove the standard test harness from tests in `src/`, and it would make it impossible to run your tests if you did.

You're right though, the documentation should make that clear.
