### ISSUE TITLE
assertion failed `(left == right)`

### ISSUE THREAD

**Issue by shahn** [japaric/criterion.rs#104]
This is my bench function:

```
fn tree_insert(c: &mut Criterion) {
    let mut arr = [0; 3];
    for i in 0..3 {
        arr[i] = i;
    }
    c.bench_function_over_inputs("insert elem",
                                 |b, &&size| {
        b.iter_with_setup(move || {
            let mut mt = MerkleTree::<sha2::Sha256>::new();
            for i in 1..size {
                mt.insert(<sha2::Sha256 as digest::Digest>::hash_elem(&A(i)));
            }
            mt
        }, |mut tree| tree.insert(<sha2::Sha256 as digest::Digest>::hash_elem(&A(size))))
    },
    arr.iter());
}

```

gives this backtrace:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some("")`,
 right: `Some("         line 0: warning: could not confirm linked axis inverse mapping function\n\taxis1: (set_min,min,testmin) = (nan,-10,nan); axis1: (set_max,max,testmax) = (90,10,90); axis2: (set_min,min) = (nan,-10); axis2: (set_max,max) = (90,10)\n\ngnuplot> plot \'-\' binary endian=little record=83 format=\'%float64\' using 1:2:3:4 with yerrorbars lt 1 lw 2 pt 7 ps 0.75 title \'mean\'\n                                                                                                                                    ^\n         line 0: x range is invalid\n\n")`', /Users/shahn/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.1.1/src/plot/mod.rs:869:12
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: criterion::plot::summarize
   8: criterion::analysis::summarize
   9: criterion::analysis::function_over_inputs
  10: criterion::Criterion::bench_function_over_inputs
  11: bench::main
  12: __rust_maybe_catch_panic
  13: std::rt::lang_start
Summarizing results of insert elem... error: bench failed

```

**Comment by bheisler** [comment]
Thanks for the bug report.

It looks like gnuplot is failing (or at least producing some warning output). Could you provide the output of `gnuplot --version`?

In the short term, you can work around this by disabling the plots for that particular benchmark. You could maybe [change your dependency](http://doc.crates.io/specifying-dependencies.html#specifying-dependencies-from-git-repositories) to use the latest revision from git and see if that helps; some of the panics have been removed.

Of course, Criterion.rs shouldn't be generating scripts that cause gnuplot to fail, but I think I'll have to add more debug output to diagnose that.

**Comment by shahn** [comment]
gnuplot --version:
gnuplot 5.2 patchlevel 2

I think updating the dependency would not help here as I checked and the panic is still present in master. Happy to run for more debug output though

**Comment by shahn** [comment]
Looks like I spoke too soon - using git for the dependency makes this work.

**Comment by shahn** [comment]
And again I spoke too soon. The panic is gone, but the generated file is zero bytes. No error is reported.

**Comment by bheisler** [comment]
Yeah, I should have been more clear - I just thought it would prevent the panic and allow you to keep benchmarking.

It would help me debug this if you can minimize your example further - it currently relies on some of your code to work.

**Comment by shahn** [comment]
The code is public, if that would work for you? https://github.com/shahn/merkle-rs/tree/benches If that is not enough I would be happy to minimize it but I'm afraid it might take a while

**Comment by shahn** [comment]
Btw, I mostly use criterion for the gnuplot graphs. I don't need benchmark comparisons etc.

**Comment by bheisler** [comment]
This should be fixed now. Unfortunately, it will probably be a few days or weeks before the next full version is released. In the meantime, you can either continue to depend on the git version (I'd suggest pinning to a specific revision for now) or, as a workaround, you could change your benchmark to avoid using 0 as an input.

Thanks again for the bug report and patience!
