### ISSUE TITLE
Add a way to disable logscale

### ISSUE THREAD

**Issue by shahn** [japaric/criterion.rs#106]
Please add a way to influence graph generation. The timing information is displayed in log scale, which is inappropriate for my data

**Comment by bheisler** [comment]
Thanks for the suggestion.

In fact, I think I might just remove the log-scaling entirely. That's what caused your earlier issue. I'm not sure the use-cases for it are sufficiently compelling to make it worth the maintenance effort at this point.

As I'm sure you've guessed, the plot generation hasn't received a lot of attention yet. So far, you seem to be the only person using the plot generation in any meaningful way. Would you mind adding your input on that to #107?
