### ISSUE TITLE
Review Plot Generation

### ISSUE THREAD

**Issue by bheisler** [japaric/criterion.rs#107]
I haven't yet put much effort into figuring out how the plot generation ought to work. This is a larger-scale issue for tracking the progress of designing and implementing the workflow for generating and using the plots.

Current issues:
* No way for user to configure plot output.
* User must manually browse to plot files in a somewhat inconvenient location and open them individually.
* Which plots should be generated? It's not clear that the current set is the best, especially as it regards the comparison of multiple implementations of a function or different inputs to a function.

It would probably be a better idea to generate an HTML report with the plots embedded like Haskell's Criterion does. This raises another question - do we want to continue using gnuplot? If we're embedding the plots in an HTML document anyway, it might be better to generate an interactive plot using Javascript. From a maintenance perspective as well, it would be nice if we could use a well-established crate for rendering the plots rather than maintaining our own. I don't know if any such thing exists at the moment however.

**Comment by shahn** [comment]
The gnuplot graph generation is what drew me to criterion. I don't feel strongly about whether the graphs are created by gnuplot or not, but not having the option of them being saved to disk automatically would be a quite sad (I tend to scroll through the graphs to notice patterns in my data. I don't really use criterion to do comparative benchmarks).

For the workflow, I think it would be best if you could separate running the benchmarks from creating the graphs. That way, if you don't like the graph options you're using - no problem, just rerun with slightly different options, the data is still there. Likewise, maybe you need to fiddle with the benchmark without wanting the overhead of creating graphs all the time. The location doesn't bother me at all, even though I can see how someone might be confused.

**Comment by bheisler** [comment]
Ah, once again I've been unclear. My apologies, I really should be more careful. I'm considering removing the automatic log-scale feature of the plots because I'm not confident that it's correct and I'm not sure it's worth the effort to fix it. The plots in general will stay, of course, though potentially redesigned.

Could you explain in more detail what sort of patterns you're looking for?

**Comment by shahn** [comment]
For example, look at the attached image which was generated by criterion: 
[insert_elem.pdf](https://github.com/japaric/criterion.rs/files/1594086/insert_elem.pdf)
There are interesting things to be learned about the data structure by analyzing this timing pattern. I want to tweak the created images, which I did using the new "save gnuplot command to disk" feature (which is just great!) which allows me to fiddle with ranges, etc. Once I'm done a high-quality svg image is produced automatically and I don't need to figure out how to export the image I'm seeing in my browser. I generally dislike working in browsers

**Comment by llogiq** [comment]
One thing I'd like to see is logarithmic scales for the plots. Also perhaps draw a box diagram like https://benchmarksgame.alioth.debian.org/u64q/which-programs-are-fastest.html – perhaps even showing individual outliers.

**Comment by bheisler** [comment]
Some small-ish things to add:

* Log-scale should be possible for those charts where it is appropriate, but the caller should request it, it shouldn't be selected automatically.
* More explanation is needed for what the charts in the HTML report mean. Haskell's Criterion includes an "understanding this report" section at the end of the report that could supply ideas.

Additionally, more work is needed on comparing different functions and different inputs. As far as I can tell from the example reports, Haskell's Criterion only generates a simple bar chart. Currently, Criterion.rs generates a very basic plot showing the lower bound/mean/upper bound of the bootstrapped statistics (which is probably not that useful) and a violin plot of the measured iteration times using a KDE function.

The violin plot is probably the right approach for comparing categorically-different measurements (eg. different functions, non-numeric inputs). As llogiq suggests, it may be useful to overlay a boxplot on top of that.

For comparing over different inputs, I think it would be appropriate to treat numeric inputs separately. It may be useful to treat those benchmarks where we have a Throughput as if they were numeric, since the size of the buffer/collection/byte array/whatever is probably more relevant than its value. In addition to the violin plot, for these inputs a line chart showing how the function(s) perform over different inputs would probably also be useful. I'd say this one should just show the point estimates of the bootstrapped distibutions to be easily read at a glance - the reader can look at the violin plot for more statistical detail.

**Comment by bheisler** [comment]
This is done for now. There's probably more to do to improve the plots but that can be another issue if/when we get there.
