### ISSUE TITLE
Is there a way to run a specific benchmark instead of the whole suite?

### ISSUE THREAD

**Issue by Proksima** [japaric/criterion.rs#109]
I might just have missed the how-to in the documentation but trying something like:

rustup run nightly cargo bench benches::my_benchmark::benchmark_1 does not seem to filter out benchmarks.

If the feature does not yet exists it would be incredibly useful as, technically, optimization often focus on a single function at the time.

**Comment by bheisler** [comment]
Yes, at least in 0.1.1, although I see that I forgot to add it to the changelog.

`cargo bench my_benchmark` should work, where `my_benchmark` is the ID string (or a substring thereof) you pass to `bench_function` and friends. If you're using a module path like you do here then  I would have expected it to run no benchmarks, so maybe something strange is happening.

It may also be that Cargo is doing something strange with your input. Maybe try `cargo bench -- my_benchmark` - the `--` separates Cargo arguments from the benchmark arguments.

I should document this better, though.

**Comment by Proksima** [comment]
I actually tried a lot of stuff including using --, module path, name only and it always just run the full suite... Could it be because I am running it using rustup run nightly? (it fails to compile on stable for me because of criterion-stats)

Here an example where I have bench IDs dot_product_1, dot_product_5, dot_product_10, etc:

> dlevac@central:~/workbench/svm-rs$ rustup run nightly cargo bench dot_product_5
    Finished release [optimized] target(s) in 0.0 secs
     Running target/release/deps/svm-fbf95d3d929f1902

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/release/deps/fct-3ac061874b905594
Benchmarking dot_product_1
> Warming up for 3.0000 s

[..]

Or:

dlevac@central:~/workbench/svm-rs$ rustup run nightly cargo bench -- dot_product_5
    Finished release [optimized] target(s) in 0.0 secs
     Running target/release/deps/svm-fbf95d3d929f1902

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/release/deps/fct-3ac061874b905594
Benchmarking dot_product_1
> Warming up for 3.0000 s

[..]

(By the way, very impressive crate, you are my life-savior as I am working on a replacement of libsvm for Rust and proper benchmarks are mandatory to succeed!)

**Comment by bheisler** [comment]
It might be, I've never tried using Criterion.rs with `rustup run`.

Could you try `rustup override set nightly; cargo bench [...]`? If that doesn't work, try changing your Cargo.toml to use the latest Git revision and see if that helps.

If none of that helps then I'll have to debug this when I get home. Is your code available?

Thanks for the kind words! I hope Criterion.rs is working well for you so far, aside from this.

**Comment by Proksima** [comment]
Tried all of the above with no luck, maybe its the new Cargo version?

dlevac@central:~/workbench/svm-rs$ rustc -V
rustc 1.23.0 (766bd11c8 2018-01-01)
dlevac@central:~/workbench/svm-rs$ cargo -V
cargo 0.24.0 (45043115c 2017-12-05)
dlevac@central:~/workbench/svm-rs$

**Comment by bheisler** [comment]
Well, I've tried this with 0.1.1 on one of my own libraries and it seems to work. Is your code available anywhere for me to look at?

Maybe double-check that you're using 0.1.1 - 0.1.0 did not have this feature,

**Comment by Proksima** [comment]
I do use 0.1.1 and I definitely can send you a tarball of my code to help you debug. However it is not yet published or widely available publicly (didn't even license the thing yet ^^')

**Comment by Proksima** [comment]
Could it be my Cargo.toml, I understood from the doc it should look a little bit like this:

[dev-dependencies]
criterion = "0.1.1"
[[bench]]
name = "fct"
harness = false
[[bench]]
name = "kernel"
harness = false

To run the benchmarks defined in <project>/benches/fct.rs and <project>/benches/kernel.rs respectively...

**Comment by Proksima** [comment]
I just tested and it seems my problem is that none of my arguments are making it in. For example I tried both `-v` and `-- -v` to get the more verbose output to no effect... Its not that annoying as my benchmarks are already separated such that I can just `rustup run nighly cargo bench --bench=dot_product` to limit it to my dot products benchmark and so on...

**Comment by bheisler** [comment]
Curiouser and curiouser.

Yes, if you could send me your code I'd be happy to try it out and see what I can see. You can email me at brookheisler@gmail.com

In the spirit of trying absolutely everything, what happens if you update rustup (`rustup self update`)?

**Comment by Proksima** [comment]
It was already updated. Will finish the submodule I am working on (even if I know the actual code is not important, I'd rather not send something too messy) and will send. Thank you for doing this!

**Comment by Proksima** [comment]
...The reason it was not working is so stupid I'm ashamed.

Most tutorial use Criterion::default() so I was using this ignoring the one passed by the command line into the function... Fixed the code and now it works.

Sorry for wasting your time... :/

**Comment by bheisler** [comment]
Ah, of course, I should have thought of that. Could you please point me to the documentation that does that? I should update it.

**Comment by Proksima** [comment]
Again, its kind of my fault, I quickly jumped right in the API documentation which sometimes use Criterion::default just as an example (did so because I wanted an example with iter_with_setup as I randomize most of the input to the method I am benchmarking). The user guide use the proper way and I was not able to find a confusing example now that I get it... ^^'

**Comment by bheisler** [comment]
Alright, well I'm glad that you've gotten it working. Thanks for the report anyway; I did need to update some documentation.
