### ISSUE TITLE
Guidelines for nanobenchmarking

### ISSUE THREAD

**Issue by nickbabcock** [japaric/criterion.rs#119]
When benching functions that execute in nanoseconds, loops are used to avoid measuring overhead of the benchmark framework. An example of this is the [byteorder benchmark](https://github.com/BurntSushi/byteorder/blob/fd3f15c08e2911dc60e4e6cb1986dc3736cd7e53/benches/bench.rs#L18-L25) shown below:

```rust
#[bench]
fn read_big_endian(b: &mut Bencher) {
    let buf = $data;
    b.iter(|| {
        for _ in 0..NITER {
            bb(BigEndian::$read(&buf, $bytes));
        }
    });
}
```

I'm assuming looping inside criterion should still be used. I'm curious if it is not a bad idea for criterion to error out if it finds that it would execute too many iterations, or if there are other guidelines to accurately write nanobenchmarks.

**Comment by bheisler** [comment]
Sorry, I'm not entirely sure what you're asking for here. Do you have a case where you believe Criterion.rs is giving incorrect measurements for small benchmarks? Otherwise, the guideline is to trust Criterion.rs - the existing timing loops are already designed to minimize the measurement overhead, so I would recommend not doing your own looping. There's a page on how Criteron.rs does its measurement and analysis [here](https://japaric.github.io/criterion.rs/book/analysis.html) that goes into more detail.

> I'm curious if it is not a bad idea for criterion to error out if it finds that it would execute too many iterations

I'm sorry, I'm not sure what you mean here. Could you elaborate?

**Comment by nickbabcock** [comment]
> Sorry, I'm not entirely sure what you're asking for here. Do you have a case where you believe Criterion.rs is giving incorrect measurements for small benchmarks?

Originally I was seeing [-30, 30]% swings in reported timings with each run on (afaik) idle machine. Thus I couldn't tell if my changes were having any effect. I tried reproducing this again, and I appear to have consistent results, so I'll keep an eye on this.

> I'm sorry, I'm not sure what you mean here. Could you elaborate?

I figured if a billion iterations were executed in 5s that criterion would be the majority of the timings. It's harder to interpret valgrind profiling results when the function benchmarked is only a small percentage of the time.

**Comment by bheisler** [comment]
>I figured if a billion iterations were executed in 5s that criterion would be the majority of the timings. It's harder to interpret valgrind profiling results when the function benchmarked is only a small percentage of the time.

Ah, I see. No, Criterion.rs only measures the elapsed time once per sample, not per-iteration (typically, 100 samples). You should be able to profile your code without any significant overhead from measurement, however small the function is.

Criterion.rs can accurately measure functions down to the single instructions. I've added a note to the FAQ to demonstrate this - [see here](https://japaric.github.io/criterion.rs/book/faq.html#how-should-i-benchmark-small-functions).

I hope that answers your question. If you continue seeing large shifts (+-3% is pretty normal, 30% isn't) in measurements on an idle machine please raise another issue with reproduction steps, that shouldn't be happening.

Thanks for trying Criterion.rs!
