### ISSUE TITLE
Avoid truncating long benchmark names

### ISSUE THREAD

**Issue by sfackler** [japaric/criterion.rs#120]
It looks like the benchmark output truncates benchmark names to 23 characters. I have some benchmarks with names longer than that, and it gets hard to tell them apart, unfortunately.

It would be great if the names weren't truncated. The time data could maybe fold to the next line if the name is too long?

**Comment by bheisler** [comment]
Thanks for trying Criterion.rs!

Yeah, I was planning to do exactly that.
