### ISSUE TITLE
bench fails due to assertion error

### ISSUE THREAD

**Issue by llogiq** [japaric/criterion.rs#121]
I tried to port the [bytecount](https://github.com/llogiq/bytecount) benchmarks to criterion (and I already like the API). However, on the larger (and thus slower) benchmarks, I invariably get the following error (backtrace enabled for helping pinpoint the problem):

```
thread 'main' panicked at 'assertion failed: slice.len() > 1 && slice.iter().all(|x| !x.is_nan())', /home/andre/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-stats-0.1.3/src/univariate/sample.rs:43:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
   6: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
   7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
   8: criterion::plot::summarize
   9: criterion::analysis::summarize
  10: criterion::analysis::function_over_inputs
  11: bench::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  15: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  16: main
  17: __libc_start_main
  18: _start
error: bench failed
```

It appears the problem stems from [stats/src/univariate/sample.rs#43](https://github.com/japaric/criterion.rs/blob/master/stats/src/univariate/sample.rs#L43). However, I have not yet sufficiently debugged to find out whether the first or second part of the condition does not hold. At the very least I suggest splitting the assert statement in two.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs.

I fixed a panic just like this a few days ago, but it isn't released yet. Could you try it with the latest git revision? If that doesn't work for you, could you share your code and benchmarks so I could reproduce and debug this issue?

**Comment by llogiq** [comment]
Thanks for maintaining it! :+1:

I'm just running it from git and the error no longer appears. Closing this issue for now. I'll wait for the release before I officially switch, though.
