### ISSUE TITLE
What do we need 1.23 for?

### ISSUE THREAD

**Issue by llogiq** [japaric/criterion.rs#124]
bytecount will currently build with Rust 1.20, but will no longer be able to benchmark with criterion (I have a PR open that I'll need to extend to make criterion optional so we can at least test.

So I wonder: What do you need the current version for?

**Comment by bheisler** [comment]
Criterion.rs uses the handlebars crate to generate HTML. That, in turn, uses pest, which requires 1.23.

I didn't realize this until after I released 0.2, but the (unwritten) policy has always been that Criterion.rs is only tested on the latest stable release. Now that it's become a problem for some users, I'll probably look at changing that policy going forward.

I'm not sure what the usual compatibility policy in the Rust ecosystem is. What would you suggest?

**Comment by llogiq** [comment]
Perhaps split the data collection and report generation in two? This would also allow us to e.g. plot timelines over multiple versions in the future.

**Comment by bheisler** [comment]
That's definitely in the long-term plan, yes.

In the short term, I suppose I could make the HTML reports a default Cargo feature in 0.2.1. That way, you could at least disable it.

**Comment by llogiq** [comment]
That'd be great for CI. Thanks.

**Comment by vks** [comment]
> In the short term, I suppose I could make the HTML reports a default Cargo feature in 0.2.1. That way, you could at least disable it.

While I wholly support this goal, please note that introducing default features is technically a breaking change for anyone using `default-features = false`. (In this case, I would expect the impact to be minimal, because it seems criterion doesn't have default features so far, so nobody should be using `default-features = false`.)

**Comment by bheisler** [comment]
Technically that's true, but I'm not too concerned about breakage with this change - no public API would change so the only way this could break code is if someone had disabled default dependencies and written scripts that expect the existence of the HTML reports, which seems pretty unlikely.

**Comment by llogiq** [comment]
Thank you! I've updated my branch to test this, it appears to work fine.
