### ISSUE TITLE
Improve documentation of benchmark setup/teardown usage

### ISSUE THREAD

**Issue by WrinklyNinja** [japaric/criterion.rs#127]
Hi, first of all thanks for this library, it's great! However, I think I'm using it wrong, because I'm spending a lot of time waiting for benchmarks with expensive setup to finish running.

The docs for `Criterion::bench_function()` include:

> The function under test must follow the setup - bench - teardown pattern:
> 
> ```
> use self::criterion::{Bencher, Criterion};
> 
> fn routine(b: &mut Bencher) {
>     // Setup (construct data, allocate memory, etc)
> 
>     b.iter(|| {
>         // Code to benchmark goes here
>     })
> 
>     // Teardown (free resources)
> }
> 
> Criterion::default().bench_function("routine", routine);
> ```

I've been using `bench_function_over_inputs()` similarly, putting expensive setup outside the `b.iter()` call, and I've been seeing very long benchmark times (1000s of seconds to benchmark functions that take < 1 ms to run). I just assumed that Criterion thought this was necessary for statistical rigour, but then I noticed that I could significantly change how much work `b.iter()` was doing without affecting the running time much, which doesn't seem right. 

I've just noticed that `Bencher.iter_with_large_setup()` exists, which I didn't spot mentioned in the getting started guide, but a quick go at using it just seems to have made things worse.

What should I be using and how? If it helps, my benchmark code is [here](https://github.com/WrinklyNinja/libloadorder/blob/master/benches/load_order.rs).

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion!

I'm not entirely sure what you should use. For the most part, I think you could do your setup once before doing any benchmarking - especially the parts that access the file system - and then clone the structure or something. The way you've structured your code here, it will repeat the file-system setup 100 times for each of your benchmarks, and file-system access is always slow. Try to do your setup in-memory and avoid writing to the disk in your benchmarks if possible. Something like this:

```
let tmp_dir = TempDir::new("libloadorder_test_").unwrap();
let mut load_order = prepare(
	game_id,
	&tmp_dir.path(),
	plugins_count,
	active_plugins_count,
);

load_order.load().unwrap();
let plugins = load_order.plugin_names();
let plugin_refs: Vec<&str> = plugins.iter().map(AsRef::as_ref).collect();

c.bench_function_over_inputs(
	"WritableLoadOrder.set_load_order()",
	|b, &&(game_id, plugins_count, active_plugins_count)| {
		  b.iter(move || load_order.set_load_order(&plugin_refs).unwrap())
	},
	LOAD_ORDERS,
);
```

`iter_with_large_setup` is mostly for benchmarks that need some setup for each iteration - eg. when benchmarking insertion into a collection, you want to make sure that each iteration is inserting into a collection of the same size.

Yeah, I should probably update the documentation.

Hope this helps!

**Comment by WrinklyNinja** [comment]
I've modified the code so that the filesystem setup happens out the `c.bench_function_over_inputs()` calls, and the benchmarks run much faster now.

I guess my main point of confusion was that I thought the function passed to `b.iter()` was the benchmark code, and the outer closure was the "fixture" code. I didn't realise that `sample_size` controls how many times the outer closure is run, I think that could be made more obvious.

Since my problem is solved, I'll close this, thanks for the clarification!
