### ISSUE TITLE
Pick a Compatibility Policy

### ISSUE THREAD

**Issue by bheisler** [japaric/criterion.rs#128]
Criterion.rs was only ever regularly tested against the latest stable version of Rust up until 0.2.0. That release caused some issues because `handlebars` depends on `pest` which requires Rust 1.23, so as a temporary measure I've made the HTML reports optional so that users can disable the dependency on `handlebars` if they need to, and added a CI build to verify that Criterion.rs builds on 1.20 if that's done.

This raises the question - what should Criterion.rs' compatibility policy be? I typically keep my projects up to date while I'm working on them, so I personally don't need any support for older versions.

My question to users: What sort of compatibility policy would make sense for you? What are some typical compatibility policies in the Rust ecosystem?

**Comment by bheisler** [comment]
Since there has been no response from users, I'm going to go ahead and tentatively commit to a "last-three-versions" policy, which means that (as of writing) Criterion.rs is only guaranteed to work on Rust 1.25 or later. Older versions may or may not work (though I think 1.23 will continue to work for a while).

**Comment by Eh2406** [comment]
The emerging standard, such as it is, is to add a test in CI with the min rust version supported. This makes it easy to see what rust version are supported and makes it hard to accidentally break that commitment. There is not currently a widely accepted standard for when a bump is necessary nor if it is a breaking change. So a policy of upping the min rust version when a commit needs it; up two "last-three-versions" sounds reasonable.
