### ISSUE TITLE
Re-enable log plots

### ISSUE THREAD

**Issue by nbigaouette** [japaric/criterion.rs#134]
Using criterion 0.2.1 the plots are shown on linear scale. Previous related conversations (#106, #107) have shown that there is interest but the implementation was buggy/not sufficient. The plots are now in linear scale since 20c369dfafe9316e19e34a5cd3aff42cfa472314.

I'm attempting to benchmark multiple algorithms which have different scaling, for example with O(N^2), O(N), O(N log N) and O(sqrt(N)).

I can't easily compare those scaling on a linear scale as the O(N^2) obviously dominates all others.

Could an option to get a logarithmic scale be added back?

Thanks a lot for this amazing crate! 👍

**Comment by nbigaouette** [comment]
Here's how it looks like:
![screen shot 2018-03-22 at 2 31 37 pm](https://user-images.githubusercontent.com/112988/37790759-cce10688-2ddd-11e8-8a55-af2a406a9282.png)

**Comment by nbigaouette** [comment]
Urg... silly me, it's already supported! :D

See http://japaric.github.io/criterion.rs/criterion/struct.PlotConfiguration.html

Here's an example:
![screen shot 2018-03-22 at 2 46 19 pm](https://user-images.githubusercontent.com/112988/37791532-d516327c-2ddf-11e8-8460-e68db21d5fd0.png)

**Comment by bheisler** [comment]
Hey, I'm glad you solved your problem. Thanks for trying Criterion.rs!
