### ISSUE TITLE
Table of contents for HTML reports

### ISSUE THREAD

**Issue by hdevalence** [japaric/criterion.rs#136]
This library is really great!

One thing that would be nice would be to generate a table of contents for the HTML reports. Right now, each benchmark's report is put into its own subdirectory of `target/criterion`, but there's no index page. It would be cool to be able to push the generated benchmark reports to a web host as a self-contained report.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs.

I agree, that would be a useful thing to have. It shouldn't be too hard to add, if you'd care to submit a pull request. Otherwise, I might get around to it the next time I do some work on Criterion.rs.
