### ISSUE TITLE
panic 'index out of bounds'

### ISSUE THREAD

**Issue by dten** [japaric/criterion.rs#139]
I'm getting a panic which i pointing to this line: https://github.com/japaric/criterion.rs/blob/master/src/plot/mod.rs#L440

I assume it's because some how i've got a lot of zeroes coming from somewhere that's not supposed to be zero but thought i'd let you know

```
     Running C:\Users\DavidHewson\Documents\Repositories\rust\la05\target\release\deps\criterion_benchmark-40c30aef1aa85bcb.exe
invert                  time:   [0.0000 ps 0.0000 ps 0.0000 ps]
                        change: [   NaN%    NaN%    NaN%] (p = 0.00 < 0.05)
                        Change within noise threshold.
thread 'main' panicked at 'index out of bounds: the len is 500 but the index is 18446744073709551615', C:\Users\David\.cargo\registry\src\github.com-1ecc6299db9ec823\criterion-0.2.2\src\plot\mod.rs:440:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: bench failed
```

**Comment by dten** [comment]
oh it seems to be when i forget to actually use `b.iter(|| {})`

**Comment by bheisler** [comment]
Huh. That's a corner case I hadn't considered before. Well spotted!

**Comment by jakubadamw** [comment]
@bheisler, could the harness report a more human-readable error in this case? I just ran into this and it took me a while before I looked here. By the way, I'm seeing it not because of a missing `b.iter()` but, as I suspect, due to the sample size/number of resamples being too low. I am also not seeing it happen deterministically. Also, the error interchanges with another one:

```
Backtrace (most recent call first):
  File "<unknown>", line 0, in core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  File "<unknown>", line 0, in <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  File "<unknown>", line 0, in <criterion::html::Html as criterion::report::Report>::measurement_complete
  File "<unknown>", line 0, in <criterion::report::Reports as criterion::report::Report>::measurement_complete
  File "<unknown>", line 0, in criterion::analysis::common
  File "<unknown>", line 0, in <criterion::benchmark::ParameterizedBenchmark<T> as criterion::benchmark::BenchmarkDefinition>::run
  File "<unknown>", line 0, in ingestion_benchmark::main
  File "<unknown>", line 0, in std::rt::lang_start::{{closure}}
  File "src/libstd/rt.rs", line 49, in std::rt::lang_start_internal::{{closure}}
  File "src/libstd/panicking.rs", line 296, in std::panicking::try::do_call
  File "src/libpanic_unwind/lib.rs", line 82, in __rust_maybe_catch_panic
  File "src/libstd/panicking.rs", line 275, in std::panicking::try
  File "src/libstd/panic.rs", line 394, in std::panic::catch_unwind
  File "src/libstd/rt.rs", line 48, in std::rt::lang_start_internal
  File "<unknown>", line 0, in main
  File "<unknown>", line 0, in __libc_start_main
  File "<unknown>", line 0, in <unknown>
  File "<unknown>", line 0, in <unknown>

The application panicked (crashed).
  called `Option::unwrap()` on a `None` value
in src/libcore/option.rs, line 378
```

No debug symbols, sorry. 🙂 It's a benchmark run after all!

**Comment by bheisler** [comment]
It does detect if you don't call `iter` and gives a specific error message for that.

Whatever you're seeing is likely a different error. Are you using the latest version of Criterion.rs? Something like that was fixed a couple versions back. If that doesn't help, could you post a new issue with more details? A reproducible test case would be great.

**Comment by smr97** [comment]
I am getting the same error, is there an updated patch for this?

**Comment by bheisler** [comment]
I was never able to reproduce that issue, so no. Do you have some benchmark code you could share that triggers this error?

**Comment by smr97** [comment]
I do, but it has several dependencies, and I am not able to produce a small self contained example for you since I am pressed for time for now. However, when I faced this issue, increasing nresamples() fixed it for me. 

Is there a minimum value that I should set it to? My benchmarks take a long time, that is why I am playing with these settings.

**Comment by bheisler** [comment]
I would advise you not to change `nresamples` - I expect it will have a very small effect on your benchmark time, but it will affect the confidence intervals generated by Criterion.

I don't think there's a minimum value, aside from that it must be positive. What did you set it to?

**Comment by smr97** [comment]
I believe I set it to 3 or 5, then upped it to 10, which fixed the issue. So, I was assuming that my benchmark closure will be run `nresamples` number of times. Is that not so?

**Comment by bheisler** [comment]
It sounds like what you want is `sample_size` - `nresamples` is used for some of the statistical analysis after the measurements are completed. Specifically, it's the number of bootstrap samples computed from the measurements, but each bootstrap sample is very fast so I don't expect it will affect your benchmark time very much.

**Comment by bheisler** [comment]
Thanks for the extra information; I was able to track down and fix a couple of panics that could happen when `nresamples` is set to a very small number. It still won't necessarily _work_ if you do that - gnuplot gives errors even if Criterion.rs doesn't panic. I've also added a warning if `nresamples` isn't at least 1000; that number is pretty arbitrary, but it should be enough to avoid problems.

**Comment by smr97** [comment]
No worries! I am sorry I couldn't help more. I haven't studied bootstrapping in detail. I just know that this is to eliminate the null hypothesis. So, can you please tell me, if I set this to 1000, will my closure be run 1000 times?

And by the way, I also reduced `sample_size` already, that helped me!

**Comment by bheisler** [comment]
No, the closure will not be run 1000 times.
