### ISSUE TITLE
Target directory names for bench_function_over_inputs with strings

### ISSUE THREAD

**Issue by robinst** [japaric/criterion.rs#142]
Hey! First off, thanks for this great tool! I have one minor issue, here's how to reproduce:

1. Use `bench_function_over_inputs` and use strings for the input such as `"foo/bar"`
2. Run the benchmark
3. Look at the file names in the `target` directory

Expected: Not sure what :).
Actual: The files look like this:

* `target/criterion/fun/`
  * `"foo/`
    * `bar"/`

While it makes sense, it's kind of unexpected and I wonder if it might be a good idea to replace special characters such as `/` and `"` before using them in file names. What do you think?

(This came up [here](https://github.com/trishume/syntect/pull/145#pullrequestreview-114178482) and I have a minimal repo to reproduce it [here](https://github.com/robinst/criterion-example-string-inputs/blob/master/benches/example.rs#L16).)

**Comment by trishume** [comment]
It's not just that the directory structure is weird and unexpected, but for me it also breaks many of the figures and links in the HTML reports because it can't find things at the weird paths.

**Comment by bheisler** [comment]
Thanks for trying Criterion.rs! Thanks for the bug report.

I figured that would cause trouble sooner or later. I'll try to fix this soon.
