### ISSUE TITLE
Way to compile benchmarks without running them?

### ISSUE THREAD

**Issue by tarcieri** [japaric/criterion.rs#144]
I would prefer not to run benchmarks in CI, both because it slows down the CI process considerably and the CI environment I'm using is not well-suited for accurate benchmarking. However, if I don't at least compile the benchmarks in CI, they have a tendency to break, e.g.

https://github.com/tendermint/signatory/pull/30

Is there any way to ensure the benchmarks compile without actually running them?

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs. I think you're looking for `cargo build --benches --all`.

**Comment by tarcieri** [comment]
Thanks for the prompt reply! That did the trick
