### ISSUE TITLE
Avoid overwriting the previous run

### ISSUE THREAD

**Issue by Marwes** [japaric/criterion.rs#150]
When I try to optimize something using the normal rust benchmarks I usually do an initial baseline run of the code before I start and then save the output in a file somewhere. Then, after making the (supposed) improvements I rerun the benchmarks again and compare the results with the baseline to see if it is has improved.

While criterion has this comparison built (which is great!) it also always overwrites the old data after each run which makes it impossible (well, really annoying) to compare against a fixed baseline. I saw the `--measure-only` flag which disables this overwriting but but unfortunately that does not display any analysis at all.

Perhaps a flag which just disables the overwriting on disk could be added?

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs, and thanks for the suggestion.

I agree, this is something I'd like to improve. Your suggestion is a reasonable way to do that.

I'm afraid I probably won't get around to implementing this right away, but pull requests would be welcome.
