### ISSUE TITLE
Alternative units

### ISSUE THREAD

**Issue by gnzlbg** [japaric/criterion.rs#151]
I am benchmarking a raytracer and would like to measure my benchmarks in ray/s. Is it possible to do this with criterion?

The book does not mention anything about this: https://japaric.github.io/criterion.rs/book/print.html

**Comment by gnzlbg** [comment]
It seems that what I want is covered by `Throughput::Elements`, the user guide docs do not cover it, and the API docs, cover it very extensively, yet AFAICT they don't show how to use it. 

I've tried:

* `b.iter(|| { ...}).throughput(Throughput::Elements(1))`
*  `c.bench_function("...", |b| { }).throughput(Throughput::Elements(1))`

and I've also tried using it in the criterion group like this:

```rust
criterion_group!{
    name = benches;
    config = Criterion::default().throughput(Throughput::Elements(1));
    targets = my_benches...
}
```

Nothing works.

**Comment by gnzlbg** [comment]
Like the whole user-guide seems to talk about a different library than the API docs, and the examples in the API docs are woefully incomplete. 

I might need https://docs.rs/criterion/0.2.3/criterion/struct.Criterion.html#method.bench to call `throughput`, but from looking at that example, I don't even know what it is supposed to mean? Where the hell does `Criterion::default` even go? Shall it float in limbo at crate item level? This does not look like anything in the user-guide at all.

**Comment by gnzlbg** [comment]
Finally solved by doing:

```rust
fn my_bench(c: &mut Criterion) {
    c.bench(
        "my_bench",
        // why do I have to name the benchmark twice?
        Benchmark::new("my_bench", move |b| {
            b.iter(|| {
                /* benchmark code */
            })
        }).throughput(Throughput::Elements(4)));
}

criterion_group!(benches, my_bench);
criterion_main!(benches);
```

That was really annoying considering that this is a one liner with the `test` crate. Honestly, the user-guide should cover all this stuff, in particular since the only stuff it covers uses `c.bench_function` which is an API that's incompatible with everything else in the library. 

Also, it would be nice if the examples in the API docs would at least be self-contained and contain `criterion_group!`/`criterion_main!` macros in them.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion. I'm sorry your first experience with the crate was not as smooth as I would have hoped.

Yes, that's the correct way to measure throughput. To answer your question; when calling Criterion::bench, you must provide a name for the function group (which is not the same thing as the `criterion_group!` macro) and a name for the function. The Benchmark struct allows you to register multiple functions (eg. to compare different implementations on the same data), provide arguments and configure the settings for one benchmark (or group of functions) - including the Throughput setting.

In response to your comment that this is a one-liner in the test crate; I disagree. If you want a one-liner, you want `bench_function`. The `bench` function is a more general part of the API intended for use cases such as this which require more detailed configuration; configuration which the `test` crate does not allow.

However, I agree, there should be a page in the user guide explaining this, including the throughput measurements and other per-benchmark configuration settings. It also hadn't occurred to me that the examples in the API docs might be unclear, but now that you've mentioned it I see what you mean. I'll clean that up as well, next time I do some work on Criterion.

**Comment by gnzlbg** [comment]
> In response to your comment that this is a one-liner in the test crate; I disagree.

The code I was porting in the test crate was just setting `bench.bytes = N` for it and using the bytes count to count element counts. So that's what I meant. 

I think it would be great to show `bench_function` and the `criterion_group!` macros in the user guide at the beginning, but quickly move towards `bench` and how it works along the guide. 

I just had to read the example in the readme to get to use `bench_function` and the other macros shown there pretty quickly, and have been able to use criterion for months just like that. 

But yesterday I was porting some code from the test crate to criterion and it was a pretty frustrating experience (sorry for the tone of my posts yesterday). Basically, this library is great, it is just the docs that are lagging a bit behind.

**Comment by bheisler** [comment]
Thanks again for the comments! I'm going to close this for now, as it's been superseded by #156.
