### ISSUE TITLE
Customizable reports

### ISSUE THREAD

**Issue by rubdos** [japaric/criterion.rs#154]
What a wonderful crate and tool!

I am currently integrating the output of the crate through a (very) simple script parsing the jsons to output stuff to GitLab CI.

![Example screenshot](https://pbs.twimg.com/media/DgCwJseW0AA_Grz.jpg:large)

The idea is that when a merge request gets filled, the benchmarks run on `master` and on the topic branch, and the difference report gets stored on a server for future review/archival.

In the merge request (see screenshot), it is quickly listed how many regressions and improvements there were, and clicking on it opens the report.

It would be nice if the report could link back to the pipeline/merge request, so I would like to add custom links in the report files when running the criterion benchmarks.

Is such a thing possible? I imagine adding a custom area with a handlebars template to put in some extra stuff.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs, and thanks for the suggestion!

Unfortunately, I'm not convinced that this is something that Criterion.rs should provide, or at least not at this time. At some point in the future, I may explore the idea of allowing users or third-party crates to provide custom reports (not to customize the built-in reports, but to replace them) but right now that seems like a lot of work for marginal benefit.

For now, I would suggest that you look into using a script of some sort to insert the desired links after the reports are generated. I can't promise that the reports will be totally stable, so your script might break from version to version, but I don't expect them to change much.

I also must stress that the JSON files are not considered to be public API and may change or disappear without warning. It is becoming clear that some form of stable, machine-readable output is needed, but this is covered in other issues threads.

**Comment by rubdos** [comment]
> Hey, thanks for trying Criterion.rs, and thanks for the suggestion!

Thanks for writing it!

> Unfortunately, I'm not convinced that this is something that Criterion.rs should provide, or at least not at this time. At some point in the future, I may explore the idea of allowing users or third-party crates to provide custom reports (not to customize the built-in reports, but to replace them) but right now that seems like a lot of work for marginal benefit.

I get that; thanks for considering though!

> For now, I would suggest that you look into using a script of some sort to insert the desired links after the reports are generated. I can't promise that the reports will be totally stable, so your script might break from version to version, but I don't expect them to change much.

I'll leave it as-is for now. It's not so urgent or needed, just a fancy addition.

> I also must stress that the JSON files are not considered to be public API and may change or disappear without warning. It is becoming clear that some form of stable, machine-readable output is needed, but this is covered in other issues threads.

I figured so much, since they are no where documented. I will follow the other issue threads associated.

---

Should we keep this issue open for future reference? If you prefer not to, feel free to close it!

**Comment by bheisler** [comment]
> Thanks for writing it!

Thanks, but most of the credit for that goes to @japaric.

Closing for now.
