### ISSUE TITLE
panic on unwrap when using valgrind

### ISSUE THREAD

**Issue by dignifiedquire** [japaric/criterion.rs#159]
I am trying to profile my code using valgrind, but when I run the compiled benchmark binary I get an unwrap panic (haven’t found the trace yet) If I run without valgrind it works fine, as well as running through valgrind if I use rusts benchmark harness. 

My suspicion is that sth changes about stdin/stdout/stderr that makes criterion upset but I haven’t been able to pinpoint it yet.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs!

Unfortunately there isn't much I can do to help here without more information. You could maybe try running Criterion.rs in debug mode ([see here](https://japaric.github.io/criterion.rs/book/criterion_rs.html#debug-output)) and see if that produces any useful output. Another option would be to use the [`--measure-only` flag](https://japaric.github.io/criterion.rs/book/user_guide/command_line.html#command-line-options) to disable all of the reporting and statistical code (which is generally a good idea when profiling Criterion.rs benchmarks anyway).

Hope this helps! If you find more information then please reopen this issue.
