### ISSUE TITLE
Small issues trying to use a benchmark as a test

### ISSUE THREAD

**Issue by KillTheMule** [japaric/criterion.rs#163]
Ref https://github.com/japaric/criterion.rs/issues/162

So, in going for a compromise as you suggested I was bitten by [this assertion](https://github.com/japaric/criterion.rs/blob/master/stats/src/univariate/sample.rs#L43). Could we simply allow length 1 here? If not, the documentation should be changed, since it only mentions disallowing length 0 for `sample_size`.

I'd send a PR, just let me know what to do about this.

**Comment by bheisler** [comment]
Ah, that's right, I'd forgotten that sample size has to be at least two. I've updated the documentation to clarify that.

Thanks for bringing this up!
