### ISSUE TITLE
Invalid type errors

### ISSUE THREAD

**Issue by KillTheMule** [japaric/criterion.rs#164]
I'm seeing errors like

```txt
14:53:28 [ERROR] caused by: invalid type: null, expected f64 at line 1 column 159
```

while trying to construct a custom `Criterion`. It seems the benchmark runs properly anyways, but I'm not sure and anyways if it's not a problem, there should be no error (and maybe, if it's really an error, the error message could be more telling).

Any idea what this is about?

**Comment by bheisler** [comment]
My first guess is that you've got a corrupted JSON file somewhere, so I'd suggest you delete the `target/criterion` directory.

If that doesn't help, could you post your code somewhere?

**Comment by KillTheMule** [comment]
Yes, that was it, thanks.

Looks like [this match](https://github.com/japaric/criterion.rs/blob/4420e5adc5fca6d11aa92b6c433ba2516fe2ed9f/src/analysis/mod.rs#L105) leads to simply logging the serde json error without telling what's going on.

Would you be open to extending `error` to improve the error message here? I'd give it a try.

**Comment by bheisler** [comment]
Certainly! Better error messages are always welcome.
