### ISSUE TITLE
User-defined printing function for Elements?

### ISSUE THREAD

**Issue by theindigamer** [japaric/criterion.rs#169]
Given that `Elements` is a generic constructor for throughput which doesn't have any particular semantics attached to it, would it be possible to expose an API to print say `MLoc` instead of `MElem`? It would be a small but nice QOL improvement.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs, and thanks for the suggestion!

I suppose this would be nice in some cases, but this seems pretty niche. I'm not sure it would be worth the (admittedly small) maintenance and API-complexity burden. I'd be willing to change my mind if there's a lot of interest though. In the meantime, perhaps you could pipe the command-line output through a `sed` script or something similar?
