### ISSUE TITLE
Strange %change formatting

### ISSUE THREAD

**Issue by saethlin** [japaric/criterion.rs#170]
One of my benchmarks just spat this out:
```
dense                   time:   [8.2225 ns 8.2308 ns 8.2401 ns]
                        change: [+3093.553356113512% +3098.7027181255644% +3103.1969274231583%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 13 outliers among 100 measurements (13.00%)
  3 (3.00%) high mild
  10 (10.00%) high severe
```

That seems like too many decimal places to me.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs!

That's quite a performance regression! Yup, after some digging it looks like Criterion.rs' formatting code isn't handling large numbers correctly. Good catch, I'll fix this in the next version.
