### ISSUE TITLE
over inputs, but each input only once

### ISSUE THREAD

**Issue by jonathanstrong** [japaric/criterion.rs#172]
hey, first day using this library and really enjoying it! 

I have been trying to do something for about an hour and can't seem to understand what the correct approach is. In my case, I want to benchmark several functions over a sequence of inputs, where the functions should be called on each input once, in order. If the inputs are out of order or the functions are called on the inputs multiple times, it destroys the validity of the benchmark. At the end of the sequence, setup needs to be triggered before the next round begins.

I can't seem to identify how to pull this off with the current api, though. Any suggestions?

**Comment by jonathanstrong** [comment]
ok, consider the following types:

```rust
enum Msg {
    A,
    B,
    // ..
}

struct State {
    n_important_things: u64,
    termperature_outside: f64,
    // ...
}

impl State {
    pub fn update(&mut self, msg: &Msg) {
        // ... do important stuff
    }
}
```

I want to benchmark `State::update` over a long list of `Msg` instances, measuring the time it takes to complete each call to `State::update` and only calling `update` with each `&Msg` once. At the end of the list of messages, trigger reset.

Why? `State` is stateful and the call to `update` depends on the previous calls to `update`, i.e. what was in the `Msg` instances. Above is a dummy example but imagine a `Msg` and corresponding `update` that are complicated - sure I can benchmark one instance of `Msg`, but what if I'm missing some pathological lag that happens for only certain types of messages?

I could benchmark calling update on a list of messages, but it's not ideal for several reasons. Mostly, as a microbenchmarking library, things are geared towards small execution times for any given benchmark.

Hopefully this makes a bit more sense?

**Comment by bheisler** [comment]
Ah, I see! Thanks for the explanation. That is a tricky one...

Criterion.rs doesn't have direct support for anything like that, I'm afraid, and adding support would be complex.

In this situation, I think I would start by adding a benchmark for each variant of `Msg` where the `State` is initialized to some known state. I would also add one or two larger benchmarks that iterate over a predefined list of messages, to hopefully provide some kind of coverage of the state space. I would also think about setting things up such that new message lists can be added easily, if and when pathological cases are discovered. It may be necessary to reduce the `sample_size` to make these larger benchmarks complete more quickly if they take a long time; the extra statistical power of the default `sample_size` is probably not necessary if the benchmarks are really long.

The problem that you'll run into (especially if your state space is large) is that it's impractical to benchmark it all. This is not too different from any other kind of testing, really; it's hard to be sure that code like this doesn't have some subtle bug that will only reveal itself after a long string of messages, let alone a performance issue. In such situations, I've found that the best thing to do is to do the best you can up-front and add regression tests later as needed.

Hope this helps!
