### ISSUE TITLE
Wrong unit used in comparison line chart

### ISSUE THREAD

**Issue by Valloric** [japaric/criterion.rs#173]
Actual units are nanoseconds, but generated line chart says it's microseconds. My guess is that it has something to do with the benchmark output units starting as nanoseconds, but ending in the microsecond range as the parameter increases.

Here's the image; I recommended opening it in a separate browser window/tab to see the unit.
![lines](https://user-images.githubusercontent.com/919444/42738879-659a3cb6-8840-11e8-85c1-23fd072fd712.png)

CLI output showing nanoseconds (and 1.8 micros at the end, not 1800 micros):

```
Running target/release/deps/hashes-c8c3fff778a5498e
big_input/crc32c/1024   time:   [189.70 ns 189.89 ns 190.11 ns]
Found 7 outliers among 100 measurements (7.00%)
  3 (3.00%) high mild
  4 (4.00%) high severe
big_input/crc32c/4096   time:   [747.70 ns 748.48 ns 749.43 ns]
Found 12 outliers among 100 measurements (12.00%)
  4 (4.00%) high mild
  8 (8.00%) high severe
big_input/crc32c/8192   time:   [1.4792 us 1.4811 us 1.4833 us]
Found 11 outliers among 100 measurements (11.00%)
  7 (7.00%) high mild
  4 (4.00%) high severe
big_input/crc32c/16384  time:   [2.9612 us 2.9651 us 2.9695 us]
Found 9 outliers among 100 measurements (9.00%)
  4 (4.00%) high mild
  5 (5.00%) high severe
big_input/seahash/1024  time:   [128.83 ns 128.98 ns 129.15 ns]
Found 11 outliers among 100 measurements (11.00%)
  3 (3.00%) high mild
  8 (8.00%) high severe
big_input/seahash/4096  time:   [477.68 ns 478.10 ns 478.58 ns]
Found 11 outliers among 100 measurements (11.00%)
  5 (5.00%) high mild
  6 (6.00%) high severe
big_input/seahash/8192  time:   [945.75 ns 946.88 ns 948.13 ns]
Found 9 outliers among 100 measurements (9.00%)
  3 (3.00%) high mild
  6 (6.00%) high severe
big_input/seahash/16384 time:   [1.8791 us 1.8815 us 1.8844 us]
Found 9 outliers among 100 measurements (9.00%)
  3 (3.00%) high mild
  6 (6.00%) high severe
```

**Comment by bheisler** [comment]
Thanks for the bug report! I haven't seen this one before. I'll look into it the next time I'm working on Criterion.rs. In the meantime, pull requests would be welcome.

**Comment by hegza** [comment]
Just dropping a comment to let you know that I've the same issue but the difference is 10^6 instead of 10^3, though I can't be certain if the remainder of the error is just because of something I did.

**Comment by hegza** [comment]
Thanks a lot! Some of those charts might end up in my master's thesis.

**Comment by bheisler** [comment]
Awesome! By the way, try setting the `CRITERION_DEBUG=1` as an environment variable before running the benchmarks. Criterion.rs will dump out the `gnuplot` scripts used to generate the charts, and then you can edit them to suit your needs.
