### ISSUE TITLE
Need `Bencher::iter_with_setup_once` for once-only setup

### ISSUE THREAD

**Issue by Valloric** [japaric/criterion.rs#174]
Today, there's `Bencher::iter_with_setup` which runs the setup function for _every_ iteration of the benchmark. This can (and does) introduce substantial measurement skew because it messes with CPU caches etc; I have a benchmark for hash functions where all times measured jump by 2x if I build my random data vec inside the setup function.

There's also `Bencher::iter_with_large_setup`, but that consumes a huge (and uncontrollable) amount of memory because it pre-creates all the input data. For my aforementioned hash function benchmarks, I generated 16 KB of random data for the hash funcs, and multiplying that by hundreds of thousands of iterations... doesn't really work well.

What I need is something like `Bencher::iter_with_setup_once`, where the setup function is called only _once_ before _any_ of the iterations start. This would be exactly what I need since my benchmarks don't mutate the input data (and most benchmarks I've ever written didn't mutate inputs either).

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.

I'm somewhat confused; why not just use `iter`? Generate your data before the call to `bench_function`, move it into the outer closure (you said you don't need to mutate it) and there should be no problem, right? Something like this:

```rust
fn my_bench(c: &mut Criterion) {
    let input = generate_input();
    c.bench_function(move |b| {
        b.iter(|| hash(input))
    });
}
```

`iter_with_setup` and `iter_with_large_setup` are intended for the case where you need to mutate or destroy the input data in the benchmark.

Additionally, using random data in your benchmarks might introduce extra variance from run-to-run. I'd recommend using a constant input in general. Criterion.rs assumes that one `cargo bench` run is doing the same work as another, and if you're changing the input that assumption may not hold.

**Comment by Valloric** [comment]
> I'm somewhat confused; why not just use iter? Generate your data before the call to bench_function, move it into the outer closure (you said you don't need to mutate it) and there should be no problem, right?

That's exactly what I'm doing right now, but the problem is that the data gets moved into the closure. So I end up having to do something like this:

```rust
fn my_bench(c: &mut Criterion) {
    let input1: Vec<_> = generate_input();
    let input2 = input.clone(); // these suck :(
    let input3 = input.clone();
    let input4 = input.clone();

    c.bench_function(move |b| {
        b.iter(|| hash1(input))
    });
    c.bench_function(move |b| {
        b.iter(|| hash2(input2))
    });
    c.bench_function(move |b| {
        b.iter(|| hash3(input3))
    });
    c.bench_function(move |b| {
        b.iter(|| hash4(input4))
    });
}
```
I'd like to avoid creating all these extra variables. If I use `iter_with_setup`, the clone call (which is expensive) happens before every iteration. If I use `iter_with_large_setup`, my memory usage becomes 16 KB * hundreds of thousands of iterations.

> Additionally, using random data in your benchmarks might introduce extra variance from run-to-run. I'd recommend using a constant input in general.

That's easily fixable by hard-coding the seed for the RNG, which is exactly what I'm doing.

**Comment by bheisler** [comment]
Ah, I see what you're looking for now. In this case, I would suggest something like this:

```
fn my_bench(c: &mut Criterion) {
    let input1: Rc<Vec<_>> = Rc::new(generate_input());
    let input2 = input.clone();
    let input3 = input.clone();
    let input4 = input.clone();

    c.bench_function(move |b| {
        b.iter(|| hash1(&*input1))
    });
    c.bench_function(move |b| {
        b.iter(|| hash2(&*input2))
    });
    // And so on
}
```

It's not much cleaner, but it does reduce memory usage. Another option would be to do something like this:

```
    c.bench_function(move |b| {
        let input = generate_input();
        b.iter(|| hash1(input))
    });
    c.bench_function(move |b| {
        let input = generate_input();
        b.iter(|| hash2(input))
    });
```

This will generate your input for each sample (typically 100 samples per benchmark) rather than each iteration.

Hope this helps!

**Comment by Valloric** [comment]
> It's not much cleaner, but it does reduce memory usage. 

Sure, but it's the "unclean code" part that was bothering me. :) Having a handful of copies of the data in RAM is not an issue (but having hundreds of thousands of copies is).

Would you be interested in a PR for `iter_with_setup_once`? I might be able to find some time... Also perfectly fine with you saying "thanks but I don't think this is something we really need." :)

**Comment by hegza** [comment]
I had the same original problem as here, though the issue of cloning into closures seems larger than this use case. I used the enclose! macro to clone, move into closure and avoid producing thousands of copies of my 2 MB matrices.

```
#[macro_use]
extern crate enclose;

fn my_bench(c: &mut Criterion) {
    let input: Vec<_> = generate_input();

    c.bench_function(enclose!((input) move |b| {
        b.iter(|| hash1(input))
    }));
    c.bench_function(enclose!((input) move |b| {
        b.iter(|| hash2(input2))
    }));
    c.bench_function(enclose!((input) move |b| {
        b.iter(|| hash3(input3))
    }));
    c.bench_function(enclose!((input) move |b| {
        b.iter(|| hash4(input4))
    }));
}
```
(untested)

**Comment by Valloric** [comment]
That `enclose!` macro looks pretty sweet! I'll try that.

**Comment by bheisler** [comment]
Yeah, this seems like a pretty niche thing. I don't think I want to expose another public method just for this, especially when you can use the `enclose!` macro or just manually clone the values instead.

Thanks for the suggestion, though. I might revisit this in the future if there's a more-compelling use case for it.
