### ISSUE TITLE
Reports from benches using Criterion::bench are not in Benchmark Index

### ISSUE THREAD

**Issue by martin-t** [japaric/criterion.rs#176]
When using the `c.bench` method as opposed to `c.bench_function`, the resulting report is not available from `target/criterion/report/index.html`. Example code:

```
#[macro_use]
extern crate criterion;

use criterion::{Benchmark, Criterion};

fn some_benchmark(c: &mut Criterion) {
    c.bench("group", Benchmark::new("benchmark", |b| b.iter(|| 1 + 1)));
}

criterion_group!(benches, some_benchmark);
criterion_main!(benches);

```

It is correctly generated in `target/criterion/group/benchmark/report/index.html`, just not shown in the main report like other benchmarks are.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs!

I haven't seen this before. I'll look into it the next time I'm working on Criterion.rs. Pull requests would be welcome, though!

**Comment by bheisler** [comment]
OK! I've confirmed that this is happening, and I have some ideas for how to fix it. Thanks again for the bug report!
