### ISSUE TITLE
Throughput in plot if configured

### ISSUE THREAD

**Issue by RCasatta** [japaric/criterion.rs#177]
I am testing a function which is more efficient per element the more elements there are.
In this case the throughput is more interesting than the time.

In the case the throughput is configured isn't better to show it in the graphs? (especially it would be great in the violin plot)

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs! Thanks for the suggestion, but this is a duplicate of #149.

**Comment by qsantos** [comment]
It looks like #149 was moved to https://github.com/bheisler/cargo-criterion/issues/9.
