### ISSUE TITLE
"No such file or directory" when running parts of benchmark

### ISSUE THREAD

**Issue by robinst** [japaric/criterion.rs#182]
With criterion v0.2.4 and a clean target directory, when I run the following in the [syntect repo](https://github.com/trishume/syntect):

```
cargo bench -- parse
```

There are some errors in the output:

```
     Running target/release/deps/highlighting-7594dd596dc32340
highlight/"parser.rs"   time:   [359.99 ms 361.81 ms 365.00 ms]
08:52:12 [ERROR] error: Failed to access file "target/criterion/highlight/\"scope.rs\"/new/sample.json": No such file or directory (os error 2)
08:52:12 [ERROR] caused by: Failed to access file "target/criterion/highlight/\"scope.rs\"/new/sample.json": No such file or directory (os error 2)
08:52:12 [ERROR] caused by: No such file or directory (os error 2)
```

The errors seem to be coming from files that were filtered out (because I only ran benchmarks with "parse" in the name).

Also, I thought those kind of names would no longer be used with #142?

(Didn't have the time to create a minimal reproducible example yet, but if it's not clear what the problem is I can do that.)

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs, and thanks for the bug report!

I think I'll have to investigate this one some more before I can say what's happening for sure. I thought the folder names were fixed now as well. I suppose it's always possible I missed something.

**Comment by robinst** [comment]
You should be able to reproduce the problem by cloning this repo: https://github.com/robinst/criterion-example-string-inputs

And then run:

    cargo bench -- foo

**Comment by bheisler** [comment]
This should be fixed in the next version. It runs your test case without issue, at least. Thanks again for the bug report!

**Comment by robinst** [comment]
Thank you!
