### ISSUE TITLE
Outdated or misleading summary plot documentation

### ISSUE THREAD

**Issue by Ralith** [japaric/criterion.rs#184]
[The book's page on benchmarking with inputs](https://japaric.github.io/criterion.rs/book/user_guide/benchmarking_with_inputs.html) suggests that `target/criterion/$BENCHMARK/summary/` will be generated when using `bench_function_over_inputs`. This was exactly what I needed, and motivated my implementation of a criterion benchmark. Unfortunately, as far as I can tell, this is not actually working in 0.2.4; no `summary` directory exists anywhere under `target/criterion`, I can't find any such chart in any of the generated reports, and it's unclear to me how to change that.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs, and thanks for letting me know about this!

Yeah, that looks like some outdated documentation, my bad. You're probably looking for the HTML report at `target/criterion/report/index.html` (or if that's not it, it should have a link to what you're looking for).

I don't think that specific chart exists anymore, but the violin plots should serve roughly the same purpose.

**Comment by Ralith** [comment]
I did find that report, and indeed it doesn't have that specific chart. The violin plots were better than nothing, but I'd really like to see something with (optionally logarithmic) input size on the horizontal axis and time on the vertical.

**Comment by hegza** [comment]
@Ralith this may be what you are looking for:

[Something like this](https://puu.sh/B5Dt2/9e10228483.png)
was generated in `/report/index.html` with something like this (with unnecessary things stripped out):
```
fn do_bench(c: &mut Criterion) {
    let plot_config = PlotConfiguration::default().summary_scale(AxisScale::Logarithmic);
    let params = vec![512, 256, 128, 64, 32, 16];

    let bench = ParameterizedBenchmark::new(
        "transpose 16",
        move |be, &data_size| be.iter(|| do_stuff(data_size)),
        params.clone(),
    );

    let bench = bench.with_function("transpose 1", move |be, &data_size| {
        // Measure
        be.iter(|| do_stuff(data_size))
    });

    c.bench(
        "transpose (CPU)",
        bench
            .throughput(|&data_size| {
                // Output throughput is size of matrix times size of data-type
                Throughput::Bytes(std::mem::size_of::<f32>() as u32 * ds as u32 * ds as u32)
            })
            .plot_config(plot_config),
    );
}
```

The axis value labeling still needs some work, I suppose. That might be possible but I haven't dug that far into the library yet.
