### ISSUE TITLE
--verbose is an unrecognized option

### ISSUE THREAD

**Issue by BurntSushi** [japaric/criterion.rs#200]
The user guide claims that something like this should work:

```
$ cargo bench -- --verbose
    Finished release [optimized] target(s) in 0.07s
     Running target/release/deps/memchr_bench-1c18928008533e3d
error: Unrecognized option: 'verbose'
error: bench failed
```

If I use `--verbose` with the benchmark runner itself, then it works:

```
$ target/release/deps/memchr-74f86389da33f583 --verbose
Benchmarking memchr1/never
Benchmarking memchr1/never: Warming up for 3.0000 s
Benchmarking memchr1/never: Collecting 100 samples in estimated 5.0055 s (363600 iterations)
Benchmarking memchr1/never: Analyzing
memchr1/never           time:   [13.240 us 13.259 us 13.281 us]
                        thrpt:  [41.720 GiB/s 41.788 GiB/s 41.850 GiB/s]
                        change: [-1.0832% -0.5004% +0.0974%] (p = 0.10 > 0.05)
                        No change in performance detected.
Found 8 outliers among 100 measurements (8.00%)
  8 (8.00%) high severe
slope  [13.240 us 13.281 us] R^2            [0.9918957 0.9918257]
mean   [13.287 us 13.394 us] std. dev.      [194.87 ns 339.96 ns]
median [13.232 us 13.296 us] med. abs. dev. [88.743 ns 148.54 ns]
```

My believe here is that the `--verbose` flag is getting passed to my crate's standard benchmark harness, which doesn't recognized it. I had thought I disabled with this in my Cargo.toml:

```
harness = false
```

but I'm guessing this just disables it for the specific criterion benchmarks, and that the normal crate benchmark runner is still going. It is easy to test that hypothesis:

```
$ cargo bench --bench memchr -- --verbose
    Finished release [optimized] target(s) in 0.07s
     Running target/release/deps/memchr-74f86389da33f583
Benchmarking memchr1/never
Benchmarking memchr1/never: Warming up for 3.0000 s
Benchmarking memchr1/never: Collecting 100 samples in estimated 5.0540 s (368650 iterations)
Benchmarking memchr1/never: Analyzing
memchr1/never           time:   [13.333 us 13.361 us 13.395 us]
                        thrpt:  [41.364 GiB/s 41.470 GiB/s 41.558 GiB/s]
                        change: [-0.4072% -0.0439% +0.3356%] (p = 0.82 > 0.05)
                        No change in performance detected.
Found 7 outliers among 100 measurements (7.00%)
  4 (4.00%) high mild
  3 (3.00%) high severe
slope  [13.333 us 13.395 us] R^2            [0.9901618 0.9899054]
mean   [13.342 us 13.419 us] std. dev.      [118.04 ns 286.76 ns]
median [13.321 us 13.362 us] med. abs. dev. [65.921 ns 131.49 ns]
```

OK, so that's good. Since I don't have any other benchmarks for this crate using the standard harness, I can disable them completely:

```
[lib]
bench = false
```

And now `cargo bench -- --verbose` works.

I've been using Rust's benchmark harness for many years, and this took me a solid 20 minutes to figure out. So I figure it's probably worth mentioning in the guide somewhere. :-)

**Comment by bheisler** [comment]
HI BurntSushi. Thanks for trying Criterion.rs! This is already mentioned in the guide ([see here](https://japaric.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options)). This is the second time someone's filed an issue about this recently, though, so I think it might not be noticeable enough where it is.

**Comment by BurntSushi** [comment]
@bheisler Ah, how embarrassing! I'm so sorry that I didn't check the FAQ first. I was stuck on `cargo bench -- --verbose` from this page: https://japaric.github.io/criterion.rs/book/user_guide/command_line_output.html

I think a link to that FAQ item around where `cargo bench -- --verbose` is mentioned would probably do the trick!

**Comment by mpawelski** [comment]
For the lazy ones (like me) that found this issue as the first google result for "criterion Unrecognized option", here's the working link:
https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
