### ISSUE TITLE
Consider using plotlib instead of calling gnuplot

### ISSUE THREAD

**Issue by lu-zero** [japaric/criterion.rs#221]
[plotlib](https://crates.io/crates/plotlib) is pure rust and builds in ~20 seconds on normal hardware.

**Comment by bheisler** [comment]
Hey, thanks for the suggestion!

It would be nice to have a pure-Rust way to generate plots, to be sure. It's great that someone's building a library like plotlib, though it does seem to be under pretty active development still.

Unfortunately, it would be a lot of work to make the switch. I haven't had much time to devote to Criterion.rs lately, so I'm reluctant to make a big change like that. On top of that, plotlib's API has not yet stabilized and I'm not sure that it supports everything that Criterion.rs would need.

I'm going to close this for now, but maybe I'll revisit this idea later once plotlib is more mature or I have more time available for things like this.
