### ISSUE TITLE
Saving new baselines should append to the reports

### ISSUE THREAD

**Issue by RReverser** [japaric/criterion.rs#224]
Currently running `-s baseline1` followed by `-s baseline2` causes output to lose all the information from `baseline1`, making it impossible to compare several baselines afterwards and build custom reports.

This is somewhat related to https://github.com/japaric/criterion.rs/issues/201 - I tried to perform such comparisons manually only to find out that after waiting ~10 minutes for benchmarks to finish, all the data from previous run was already lost :(

**Comment by bheisler** [comment]
Hey, thanks for the suggestion!

I'm afraid I don't quite understand what you're looking for here. Saving a second baseline doesn't lose all of the information from the previous benchmarks. If it did, Criterion.rs wouldn't be able to use them for comparisons later. Could you elaborate more?

**Comment by RReverser** [comment]
That's odd, it definitely is what I saw - I saved one named baseline with `-s master` and then another with `-s branch` and then tried to make a third run with `-b master` but it couldn't find that named baseline anymore, and recursive grep in `target/criterion` also found just `branch` but no mention of `master`.

**Comment by RReverser** [comment]
Can't reproduce again, so maybe I just did something stupid.
