### ISSUE TITLE
Support per-iteration setup

### ISSUE THREAD

**Issue by kmcallister** [japaric/criterion.rs#23]
For example, constructing a buffer that will be consumed by the iteration. This needs to not be counted in the elapsed time, but it's hard to do that without per-iteration timing overhead.

I opened this as a ticket for `libtest`'s benchmarking (rust-lang/rust#18043) but if `criterion.rs` added support first, I would switch for sure.

**Comment by apasel422** [comment]
Was any progress made on this?

**Comment by japaric** [comment]
Implemented in #62
