### ISSUE TITLE
[question] benchmarking cdylib crates

### ISSUE THREAD

**Issue by tiras-j** [japaric/criterion.rs#237]
So - I've been trying to setup criterion benchmarking for a crate that builds "cdylib" and obviously ran into the issue where the bench build can't `extern crate <mycdylibcrate>` since it requires a rust-dep and not a binary dep.

I've fixed this by adding a "rlib" crate target to the crate output that is able to be depended upon by the benchmark build - however for some reason adding this target increases the size of the "cdylib" (in my particular case the `.so`) by 100% (2MB -> 4MB about) which is not an acceptable side-effect.

Instead I've found another workaround that involves conditionally exporting a `rustc-link-search` path to include the "cdylib" binary and build a simple symbol mapping in the benchmark code (basically benchmarking through the _actual_ FFI C-interface). This works - but of course requires that the release binary being pre-built (via something like `cargo build --release`) which doesn't occur natively in the `cargo bench` process afaict. This works as a small workaround but of course is a bit annoying.

Anyways - I was wondering if there were any suggestions for setting up benchmarks for a "cdylib" crate? And tangentially if anyone happens to know why adding a "rlib" additional crate target somehow inflates the size of the "cdylib" target dramatically... which is just weird.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs! Thanks for your patience.

Unfortunately, I have no experience with cdylib crates. Benchmarking through the C FFI interface seems like a good way to go, albeit not easily supported by Cargo. 

Another option which might work but takes some effort would be to set up a regular Rust crate  with most of your code, and then a thin cdylib wrapper crate which exports the C interface and delegates to the inner crate. Then your benchmarks could depend directly on the Rust code. Building a core library and a thin wrapper is pretty common when creating application crates.

I'm afraid I have no idea what might be causing your rlib/.so problem - that might be a good question for the compiler team.

**Comment by tiras-j** [comment]
Thanks @bheisler!

Yep - I'll probably end up refactoring the library into a core rust crate and a thin FFI shim, seems cleaner anyhow, better separation of concerns and all. If you're curious about how the crate-type-changing-binary-size turned out, [the compiler actually abandons LTO if any target isn't able to perform it](https://github.com/rust-lang/rust/issues/55942), which of course means adding `rlib` which isn't LTO enabled will then disable it for all other types (in this case `cdylib` and `staticlib`). 

Closing this ticket, thanks so much for the response!
