### ISSUE TITLE
Can't benchmark programs that initialize a logger

### ISSUE THREAD

**Issue by MasonRemaley** [japaric/criterion.rs#240]
Criterion initializes its own logger, preventing it from being used to benchmark loggers or projects that initialize loggers. Is the logger that's set up right now important to Criterion's functionality, or might it be possible to let the user set up the logger themselves?

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs! Thanks for your patience.

The logger isn't really critical, no. I hadn't considered that it might clash with user code, but in retrospect it seems obvious.

There isn't currently a way to disable it, nor a easy way to expose that option to the user. It would probably be best to just remove the standard logging code entirely and roll my own thing that does just what Criterion.rs needs (not much) and wouldn't clash with user code at all.

**Comment by MasonRemaley** [comment]
No problem, thanks for the library! :)

And yeah it wouldn't have occurred to me either--it took me a second to realize what was going on, then I felt silly for not having thought of it.

Looking through the code briefly, unless I missed anything, it seems like the only function that would be affected by switching from using a logger to plain print statements would be `pub(crate) fn log_error(e: &Error)` since it only logs the backtrace if debug statements are turned on.

I'm not sure exactly how `log_error` is used for internally--do you think it'd be possible to get away with always/never logging the back traces? Or if the backtraces are just for debugging criterion itself maybe we could just add a feature that enables them?

**Comment by MasonRemaley** [comment]
Missed the notification when this was resolved--thanks for the fix!
