### ISSUE TITLE
Add examples to doc home page

### ISSUE THREAD

**Issue by seanmonstar** [japaric/criterion.rs#31]
- An example of what the code looks like, so I know how different it would be from `test::Bencher`.
- An example of what the output looks like, so I know what I gain from switching.

**Comment by bheisler** [comment]
This issue is pretty old at this point, but I've added a [user guide](https://japaric.github.io/criterion.rs/book/criterion_rs.html) which I hope should cover this. If not, let me know and I'll try to improve the documentation as needed.
