### ISSUE TITLE
Run benchmarks on inputs of varying size?

### ISSUE THREAD

**Issue by gibiansky** [japaric/criterion.rs#48]
Is there a way to use this library to investigate dependence of input size on runtime? e.g. run benchmarks on different size of inputs.

**Comment by japaric** [comment]
Yes, there is a [`bench_with_inputs`](http://japaric.github.io/criterion.rs/criterion/struct.Criterion.html#method.bench_with_inputs) method that does this.

It generates a plot (1) where you can visualize the relationship between the runtime and the inputs.

![means](https://cloud.githubusercontent.com/assets/5018213/6119614/41509936-b099-11e4-9c12-2149bb19f4ff.png)

That's the example from the docs (2), measurement of the allocation + deallocation time of a zeroed `Vec` for different sizes.

(1) you need gnuplot, the output plots reside at .criterion/$BENCH/**/*.svg
(2) `Vec::from_elem` is no more, instead I measured `iter::repeat(0u8).take(n).collect()`.
