### ISSUE TITLE
Publish to Crates.io?

### ISSUE THREAD

**Issue by polyfractal** [japaric/criterion.rs#52]
Hi!  Criterion is a wonderful library, and I've been using it locally for a lot of benchmarking.  The problem is that I have a crate I want to publish to Crates.io ... but it depends on Criterion.  Since Criterion is not on  Crates, I'm unable to publish because cargo requires all dependencies to come from the same source (e.g. either all from git, or all from crates.io).

Would be fantastic if Criterion could get published, to make it easier to use in various projects!

**Comment by polyfractal** [comment]
Bump to this?  I have to keep [commenting Criterion out](https://github.com/polyfractal/bounded-spsc-queue/commit/acf6c5421667c34bb1440deabf6ecf70027111cb) whenever I publish. :(

Criterion works well enough right now imo, I think publishing a 0.0.1 would be fine. :)

**Comment by bheisler** [comment]
Criterion.rs has been published to Crates.io. Thanks for your patience!

    [dev-dependencies]
    criterion = "0.1.0"
