### ISSUE TITLE
MultiModifier

### ISSUE THREAD

**Issue by MarkSwanson** [japaric/criterion.rs#54]
FYI I upgraded to rust 1.0 and found this:

macros/src/lib.rs:21:9: 21:17 error: use of deprecated item: replaced by MultiModifier, #[deny(deprecated)] on by default
/git/checkouts/criterion.rs-b221423a0cb2a2ed/master/macros/src/lib.rs:21         Modifier(Box::new(expand_meta_criterion)));
Using #[allow(deprecated)] makes it compile atm.

**Comment by japaric** [comment]
criterion is now working with a recent nightly.

**Comment by MarkSwanson** [comment]
Great!
