### ISSUE TITLE
Support variant metrics - MB/s, items/s, etc

### ISSUE THREAD

**Issue by RAOF** [japaric/criterion.rs#84]
There are a lot of algorithms for which seconds/iteration can be easily transformed into a more useful metric.

For example, I'm writing a delta-compressor, and so MB/sec would be a more graspable metric.

API-wise, it seems that this could be done by adding a mapping function to the Criterion pipeline. Something like:

    Criterion::default()
        .with_metric(|time, test_data| { test_data.len() / time })
        .bench_function_over_inputs(|b, data| {...});

**Comment by bheisler** [comment]
Hey! Thanks for the suggestion.

I probably won't get around to adding this right away, but I agree that these are useful metrics to have, and this is a use case I'd like to support eventually. I think it would take some internal refactoring work before something like this could be easily added, though.

**Comment by Eh2406** [comment]
This may be a separate thought... but I have an algorithm the Should be `O(n^2)`. I could use the transform to test that more directly!

**Comment by RAOF** [comment]
It would be nice to get the X-axis of the graphs for multiple-data benchmarks separated by value, rather than equally spaced, too 😀.

I've learnt that you can do a special case of this with the built-in bencher by setting b.bytes in the #[bench]...
