### ISSUE TITLE
Add Example CI Configurations

### ISSUE THREAD

**Issue by bheisler** [japaric/criterion.rs#89]
It would be useful for downstream projects to use Criterion.rs in their CI pipeline to detect regressions in pull requests and similar. Add documentation and recommendations on how that could be achieved.

**Comment by bheisler** [comment]
One approach to doing this would be to clone the repo again and checkout master, run the benchmarks, checkout the pull-request commit and run again, as recommended by https://beachape.com/blog/2016/11/02/rust-performance-testing-on-travis-ci/.

A major problem with this approach is that there will be a great deal of variability in the results. Since cloud providers typically run builds inside containers or VM's alongside unknown other processes sharing the same machine there's no real way to benchmark accurately. This documentation will need to be very clear that benchmark results taken in such an uncontrolled environment should not be relied upon. Possibly Criterion can be enhanced to offer better support for this use case - eg. by allowing the user to override the noise threshold on the command line.

**Comment by bheisler** [comment]
I've actually done some measurements of the noise involved in benchmarking on a cloud-CI service, and it's pretty significant. See the results at 

https://bheisler.github.io/post/benchmarking-in-the-cloud/

I'm going to close this for now. Perhaps at some point in the future we can enhance Criterion.rs to produce stable results despite the noise from the cloud CI servers, but for now the advice is that any benchmarks performed are likely too unreliable to be useful.

**Comment by torhovland** [comment]
An easier option that would be good enough in many cases is to be able to set a threshold and fail the benchmark if it exceeds it. But I cannot find a way to do this.
