### ISSUE TITLE
Work with stable

### ISSUE THREAD

**Issue by droundy** [japaric/criterion.rs#90]
If the only blocker is black_box, then perhaps for functions that return certain types we could have alternative mechanisms? e,g, calling functions with different input and collecting the output with a summation?

**Comment by bheisler** [comment]
A stable-compatible release is definitely planned. Most of the nightly-only code lives in [stats.rs](https://github.com/japaric/stats.rs), so it isn't just `black_box`. I think most of it should be easily converted to work on stable. The [bencher crate](https://github.com/bluss/bencher) has a workaround for `black_box` as well.

There's been a lot of requests for a stable-compatible version. I probably won't get to this right away, but keep watching this space over the next few weeks. If someone out there would like to submit a pull request, I'd be happy to help.

**Comment by droundy** [comment]
Thanks for the quick and positive response!
