### ISSUE TITLE
Replace rustc_serialize with Serde

### ISSUE THREAD

**Issue by bheisler** [japaric/criterion.rs#91]
The rustc_serialize crate is officially deprecated in favor of Serde. We should update the file system code to use Serde.

Difficulty: Easy

**Comment by bheisler** [comment]
This should largely be a matter of updating the code in `src/fs.rs` which does the serialization/deserialization and adding the appropriate derives in the few places where the `rustc_serialize` derives are used.

It's likely that switching to Serde will change the serialized form of some of the files. That's not a big deal in itself, because the stored files are quite transient anyway. Currently though, we panic if we can't deserialize a file. The load function at least will have to be updated to return a result so that we can handle this case by proceeding as if the file doesn't exist.

**Comment by maccam912** [comment]
Just submitted a PR that attempts to switch over. All the tests pass, but I don't use this crate for any projects of my own so if there are known projects that could test that everything still works that would help out.

**Comment by bheisler** [comment]
Thanks!
